In [29]:
import numpy as np
from sklearn import datasets as ds
from sklearn.model_selection import train_test_split # split dataset into train and test sets

# 1. Data preparation
iris = ds.load_iris()
X = iris.data # feature vectors
y = iris.target

print(X.shape, y.shape)
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size = 0.2) # test_size % of test set

print('training set', X_train.shape, y_train.shape)
print('test set', X_test.shape, y_test.shape)

(150, 4) (150,)
training set (120, 4) (120,)
test set (30, 4) (30,)


In [30]:
# 2. Model training
# KNN is an instance-based algorithm, and 
# it does not have the actual training


In [31]:
# 3. Prediction and evaluation
# evaluation metric: error rate : % of data samples missclassified

# prediction: 1) find the K nearest neighbors; 2)voting to predict

In [32]:
#1) find the k nns for an input data sample
def findKNgbrs(x_star, X_train, K = 5):
    '''find K nearest neighbors for a given data sample in X_train
        
        input:
            x_star: new data sample. Shape 1 by 4
            X_train:
        return:
            K nearest neighbors
    '''
    # calculate the Euclidean distance 
    n = X_train.shape[0] # number of data samples in X_train
    dis = np.zeros((n, 1)) # initialize n 0 distances
    inx = 0
    for x in X_train:
        d = np.sqrt(np.sum((x_star-x)*(x_star-x)))
        dis[inx] = d
        inx = inx + 1
        
    # find the k nearest neighbors using a sorting algorithm
    ind = np.argsort(dis, axis = 0)
    
    return ind[:K] # return the indices for the K nns

x_star = X_test[0]
print(x_star)
k_inx = findKNgbrs(x_star, X_train, K=5)
print(k_inx)

[4.9 3.  1.4 0.2]
[[ 29]
 [ 67]
 [110]
 [  3]
 [106]]


In [33]:
#prediction function
def prediction(x_train, x_test, y_train, k):
    """
    x_test: a single test sample
    x_train: training set
    y_train: training labels
    k: number of nearest neighbors

    return: predicted label
    """
    y_pred = np.zeros(len(x_test.shape[0]))
    
    for i in range(len(x_test)):

        k_inx = findKNgbrs(i, x_train, k)
        k_labels = y_train[k_inx]
        counts = np.bincount(k_labels.reshape((5,)), minlength = 2)
        y_pred[i] = np.argmax(counts)
    
    return y_pred

In [34]:
# prediction
# check the class lables of the k nns
k_labels = y_train[k_inx]
print(k_labels)
#print(k_labels.reshape(5,))

counts = np.bincount(k_labels.reshape((5,)), minlength = 2)
print(counts)

y_pred =np.argmax(counts)
print('the prediction is', y_pred)

[[0]
 [0]
 [0]
 [0]
 [0]]
[5 0]
the prediction is 0


In [35]:
# afterclass practice
#1. how do we calculate the predictions for all test data samples


#2. calculate the error rate on the test set
# try to use differnt K


In [36]:
#4. model persistance

